# Generated by Django 5.0.4 on 2024-05-19 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apariencia',
            fields=[
                ('id_apar', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id_color', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Glicol',
            fields=[
                ('glicol_rang_id', models.AutoField(primary_key=True, serialize=False)),
                ('min_glicol', models.IntegerField()),
                ('max_glicol', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InfoAditivo',
            fields=[
                ('adtv_id', models.AutoField(primary_key=True, serialize=False)),
                ('adtv_nom', models.CharField(blank=True, max_length=60, null=True)),
                ('adtv_dens', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('insumo_id', models.AutoField(primary_key=True, serialize=False)),
                ('in_nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('in_desc', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Olor',
            fields=[
                ('olor_id', models.AutoField(primary_key=True, serialize=False)),
                ('olor_nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ph',
            fields=[
                ('id_rang_ph', models.AutoField(primary_key=True, serialize=False)),
                ('ph_min', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ph_max', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Mezcla',
            fields=[
                ('mezcla_id', models.AutoField(primary_key=True, serialize=False)),
                ('pp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vv', models.DecimalField(decimal_places=2, max_digits=5)),
                ('info_aditivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.infoaditivo')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_nom', models.CharField(max_length=50)),
                ('prod_ph', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('prod_glicol', models.IntegerField(blank=True, null=True)),
                ('prod_fp', models.IntegerField(blank=True, null=True)),
                ('prod_grav_esp', models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True)),
                ('prod_api', models.CharField(blank=True, max_length=50, null=True)),
                ('prod_tk_agua', models.IntegerField(blank=True, null=True)),
                ('prod_tk_prod', models.IntegerField(blank=True, null=True)),
                ('apariencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.apariencia')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.color')),
                ('glicol_rang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.glicol')),
                ('mezcla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.mezcla')),
                ('olor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.olor')),
                ('ph', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.ph')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
