# Generated by Django 5.0.4 on 2024-06-07 07:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoAditivo',
            fields=[
                ('adtv_id', models.AutoField(primary_key=True, serialize=False)),
                ('adtv_nom', models.CharField(blank=True, max_length=60, null=True)),
                ('adtv_dens', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('insumo_id', models.AutoField(primary_key=True, serialize=False)),
                ('insumo_nom', models.CharField(blank=True, max_length=60, null=True)),
                ('insumo_vol', models.DecimalField(decimal_places=1, max_digits=3)),
                ('insumo_env_por_caja', models.DecimalField(decimal_places=1, max_digits=3)),
                ('insumo_cajas_por_pallet', models.DecimalField(decimal_places=1, max_digits=3)),
                ('insumo_desc', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('producto_nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RestVistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('acces_view1', 'can acces view 1'), ('acces_view2', 'can acces view 2'), ('acces_view3', 'can acces view 3'), ('acces_view4', 'can acces view 4'), ('acces_view5', 'can acces view 5')],
            },
        ),
        migrations.CreateModel(
            name='ProdCopec',
            fields=[
                ('prod_copec_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_copec_cod', models.CharField(blank=True, max_length=10, null=True)),
                ('prod_copec_nom', models.CharField(blank=True, max_length=60, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='LoteProd',
            fields=[
                ('lote_prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('lote_prod_fecha', models.DateField(default=datetime.date.today)),
                ('volumen_odp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volumen_prod', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tk_agua', models.CharField(blank=True, max_length=5, null=True)),
                ('tk_prod', models.CharField(blank=True, max_length=5, null=True)),
                ('lote_mp', models.CharField(blank=True, max_length=5, null=True)),
                ('fecha_ven_mp', models.DateField(default=datetime.date.today)),
                ('lote_colorante', models.CharField(blank=True, max_length=5, null=True)),
                ('fecha_ven_colorante', models.DateField(default=datetime.date.today)),
                ('lote_aromatizante', models.CharField(blank=True, max_length=5, null=True)),
                ('fecha_ven_aromatizante', models.DateField(default=datetime.date.today)),
                ('num_pedido_asr', models.CharField(blank=True, max_length=5, null=True)),
                ('lote_asr', models.CharField(blank=True, max_length=5, null=True)),
                ('fecha_ven_asr', models.DateField(default=datetime.date.today)),
                ('freezing_point', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('ph', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('glicol', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('olor', models.CharField(blank=True, max_length=10, null=True)),
                ('apariencia', models.CharField(blank=True, max_length=5, null=True)),
                ('sellos_tapas', models.CharField(blank=True, max_length=5, null=True)),
                ('valvulas', models.CharField(blank=True, max_length=5, null=True)),
                ('estado_aceptado', models.CharField(blank=True, max_length=10, null=True)),
                ('estado_produccion', models.CharField(blank=True, default='PENDIENTE', max_length=10)),
                ('patente', models.CharField(blank=True, max_length=5, null=True)),
                ('cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('prod_copec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.prodcopec')),
            ],
        ),
        migrations.CreateModel(
            name='CompProducto',
            fields=[
                ('comp_producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('pp', models.DecimalField(decimal_places=5, max_digits=5)),
                ('vv', models.DecimalField(decimal_places=5, default=1.0, max_digits=6)),
                ('info_aditivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.infoaditivo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='StockAditivo',
            fields=[
                ('stock_ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_ad_cant_lt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nomAditivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.infoaditivo')),
            ],
        ),
        migrations.CreateModel(
            name='StockInsumo',
            fields=[
                ('stock_in_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_in_cant_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='StockProducto',
            fields=[
                ('stock_producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_prod_cant_vol', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_prod_cant_uni', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prod_copec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.prodcopec')),
            ],
        ),
    ]
