# Generated by Django 5.0.4 on 2024-06-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despacho',
            name='tipo_despacho',
            field=models.CharField(default='PENDIENTE GUIA DESPACHO', max_length=50),
        ),
    ]
