# Generated by Django 5.0.4 on 2024-05-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('productos_id', models.AutoField(primary_key=True, serialize=False)),
                ('productos_nom', models.CharField(max_length=50)),
            ],
        ),
    ]
