# Generated by Django 5.0.4 on 2024-06-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compproducto',
            name='pp',
            field=models.DecimalField(decimal_places=5, max_digits=6),
        ),
    ]
