# Generated by Django 5.0.4 on 2024-06-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_delete_restvistas'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestVistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('access_view1', 'can acces view 1'), ('access_view2', 'can acces view 2'), ('access_view3', 'can acces view 3'), ('access_view4', 'can acces view 4'), ('access_view5', 'can acces view 5')],
            },
        ),
    ]
