# Generated by Django 5.0.4 on 2024-05-21 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompProducto',
            fields=[
                ('comp_producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('pp', models.DecimalField(decimal_places=5, max_digits=5)),
                ('vv', models.DecimalField(decimal_places=5, max_digits=5)),
                ('info_aditivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.infoaditivo')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
            ],
        ),
    ]
