# Generated by Django 5.0.4 on 2024-05-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_compproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compproducto',
            name='vv',
            field=models.DecimalField(decimal_places=5, default=1.0, max_digits=5),
        ),
    ]
