# Generated by Django 5.0.4 on 2024-06-07 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_restvistas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestVistas',
        ),
    ]
