# Generated by Django 5.0.4 on 2024-06-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_delete_restvistas'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestVistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('access_cruds', 'can access cruds'), ('access_crud_inv_bodega', 'can access crud_inv_bodega'), ('access_crud_orden_prod', 'can access crud_orden_prod'), ('access_crud_calidad', 'can access crud_calidad'), ('access_crud_guias_despacho', 'can access crud_guias_despacho'), ('access_crud_despacho', 'can access crud_despacho')],
            },
        ),
    ]
