# Generated by Django 5.0.4 on 2024-06-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_rename_num_pedido_asr_loteprod_num_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteprod',
            name='apariencia',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='loteprod',
            name='lote_aromatizante',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='loteprod',
            name='lote_asr',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='loteprod',
            name='lote_colorante',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='loteprod',
            name='lote_mp',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='loteprod',
            name='num_pedido',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='loteprod',
            name='patente',
            field=models.CharField(default='N/A', max_length=8),
        ),
        migrations.AlterField(
            model_name='loteprod',
            name='sellos_tapas',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='loteprod',
            name='valvulas',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
