# Generated by Django 5.0.4 on 2024-05-22 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_compproducto_vv'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAditivo',
            fields=[
                ('stock_ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_ad_cant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nomAditivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.infoaditivo')),
            ],
        ),
        migrations.CreateModel(
            name='StockProducto',
            fields=[
                ('stock_producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_prod_cant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comp_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.compproducto')),
            ],
        ),
    ]
