# Generated by Django 5.0.4 on 2024-06-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_insumo_insumo_cajas_por_pallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='producto_nom',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
