# Generated by Django 5.0.4 on 2024-05-22 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_stockaditivo_stockproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockProductos',
            fields=[
                ('stock_producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_prod_cant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productos', models.ForeignKey(default='abcd1', on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
            ],
        ),
    ]
