# Generated by Django 5.0.4 on 2024-06-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_producto_producto_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteprod',
            name='freezing_point',
            field=models.CharField(default='N/A', max_length=6),
        ),
        migrations.AlterField(
            model_name='loteprod',
            name='glicol',
            field=models.CharField(default='N/A', max_length=6),
        ),
        migrations.AlterField(
            model_name='loteprod',
            name='ph',
            field=models.CharField(default='N/A', max_length=6),
        ),
    ]
