# Generated by Django 5.0.4 on 2024-05-22 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_stockproductos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='apariencia',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='color',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='glicol_rang',
        ),
        migrations.RemoveField(
            model_name='mezcla',
            name='info_aditivo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='mezcla',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='olor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ph',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stockproducto',
            name='comp_producto',
        ),
        migrations.DeleteModel(
            name='Apariencia',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Glicol',
        ),
        migrations.DeleteModel(
            name='Mezcla',
        ),
        migrations.DeleteModel(
            name='Olor',
        ),
        migrations.DeleteModel(
            name='Ph',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='StockProducto',
        ),
    ]
