# Generated by Django 5.0.4 on 2024-05-22 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_remove_producto_apariencia_remove_producto_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproductos',
            name='productos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos'),
        ),
    ]
