# Generated by Django 5.0.4 on 2024-05-26 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_stockproductos_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compproducto',
            name='info_aditivo',
        ),
        migrations.RemoveField(
            model_name='compproducto',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='stockaditivo',
            name='nomAditivo',
        ),
        migrations.DeleteModel(
            name='Insumo',
        ),
        migrations.RemoveField(
            model_name='stockproductos',
            name='productos',
        ),
        migrations.DeleteModel(
            name='CompProducto',
        ),
        migrations.DeleteModel(
            name='InfoAditivo',
        ),
        migrations.DeleteModel(
            name='StockAditivo',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.DeleteModel(
            name='StockProductos',
        ),
    ]
