# Generated by Django 4.2.2 on 2024-05-26 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0012_remove_compproducto_info_aditivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoAditivo',
            fields=[
                ('adtv_id', models.AutoField(primary_key=True, serialize=False)),
                ('adtv_nom', models.CharField(blank=True, max_length=60, null=True)),
                ('adtv_dens', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('insumo_id', models.AutoField(primary_key=True, serialize=False)),
                ('insumo_nom', models.CharField(blank=True, max_length=60, null=True)),
                ('insumo_vol', models.DecimalField(decimal_places=1, max_digits=3)),
                ('insumo_env_por_caja', models.DecimalField(decimal_places=1, max_digits=3)),
                ('insumo_cajas_por_pallet', models.DecimalField(decimal_places=1, max_digits=3)),
                ('insumo_desc', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdCopec',
            fields=[
                ('prod_copec_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_copec_cod', models.CharField(blank=True, max_length=10, null=True)),
                ('prod_copec_nom', models.CharField(blank=True, max_length=60, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('producto_nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StockProducto',
            fields=[
                ('stock_producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_prod_cant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prod_copec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.prodcopec')),
            ],
        ),
        migrations.CreateModel(
            name='StockInsumo',
            fields=[
                ('stock_in_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_in_cant_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='StockAditivo',
            fields=[
                ('stock_ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_ad_cant_lt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nomAditivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.infoaditivo')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='prodcopec',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
        migrations.CreateModel(
            name='CompProducto',
            fields=[
                ('comp_producto_id', models.AutoField(primary_key=True, serialize=False)),
                ('pp', models.DecimalField(decimal_places=5, max_digits=5)),
                ('vv', models.DecimalField(decimal_places=5, default=1.0, max_digits=6)),
                ('info_aditivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.infoaditivo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
    ]
