# Generated by Django 4.2.2 on 2024-05-26 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodcopec',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='prodcopec',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stockaditivo',
            name='nomAditivo',
        ),
        migrations.RemoveField(
            model_name='stockinsumo',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='stockproducto',
            name='prod_copec',
        ),
        migrations.DeleteModel(
            name='CompProducto',
        ),
        migrations.DeleteModel(
            name='InfoAditivo',
        ),
        migrations.DeleteModel(
            name='Insumo',
        ),
        migrations.DeleteModel(
            name='ProdCopec',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='StockAditivo',
        ),
        migrations.DeleteModel(
            name='StockInsumo',
        ),
        migrations.DeleteModel(
            name='StockProducto',
        ),
    ]
