# Generated by Django 5.0.4 on 2024-05-28 00:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteProd',
            fields=[
                ('lote_prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('lote_prod_fecha', models.DateField(default=datetime.date.today)),
                ('volumen_odp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volumen_prod', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tk_agua', models.CharField(blank=True, max_length=5, null=True)),
                ('tk_prod', models.CharField(blank=True, max_length=5, null=True)),
                ('lote_mp', models.IntegerField()),
                ('fecha_ven_mp', models.DateField(default=datetime.date.today)),
                ('lote_colorante', models.IntegerField()),
                ('fecha_ven_colorante', models.DateField(default=datetime.date.today)),
                ('lote_aromatizante', models.IntegerField()),
                ('fecha_ven_aromatizante', models.DateField(default=datetime.date.today)),
                ('num_pedido_asr', models.CharField(blank=True, max_length=5, null=True)),
                ('lote_asr', models.IntegerField()),
                ('fecha_ven_asr', models.DateField(default=datetime.date.today)),
                ('freezing_point', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=4)),
                ('glicol', models.DecimalField(decimal_places=2, max_digits=4)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('olor', models.CharField(blank=True, max_length=10, null=True)),
                ('apariencia', models.CharField(blank=True, max_length=5, null=True)),
                ('sellos_tapas', models.CharField(blank=True, max_length=5, null=True)),
                ('valvulas', models.CharField(blank=True, max_length=5, null=True)),
                ('estado_aceptado', models.CharField(blank=True, max_length=10, null=True)),
                ('estado_produccion', models.CharField(blank=True, default='PENDIENTE', max_length=10)),
                ('patente', models.CharField(blank=True, max_length=5, null=True)),
                ('cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('prod_copec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.prodcopec')),
            ],
        ),
    ]
