# Generated by Django 5.0.4 on 2024-06-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0018_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
