# Generated by Django 5.0.4 on 2024-06-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
